# Generated by Django 3.0.2 on 2020-02-15 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='run_date',
            field=models.DateField(blank=True, default=datetime.datetime(2050, 1, 1, 1, 0)),
        ),
    ]
