# Generated by Django 3.0.2 on 2020-02-11 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(blank=True, max_length=500, null=True)),
                ('EventCity', models.CharField(blank=True, max_length=50, null=True)),
                ('EventState', models.CharField(blank=True, max_length=50, null=True)),
                ('EventUrl', models.CharField(blank=True, max_length=1000, null=True)),
                ('EventTypes', models.CharField(blank=True, max_length=500, null=True)),
                ('EventDate', models.DateTimeField(blank=True, null=True)),
                ('RegCloseDate', models.DateTimeField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
